server:
  port: ${prod.admin.server.port}
spring:
  security:
    user:
      name: ${prod.admin.security.user.name}                               # security默认用户名
      password: ${prod.admin.security.user.password}                       # security默认密码
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver                           # mysql数据库连接驱动
    url: ${prod.admin.datasource.url}                                      # mysql数据链接
    username: ${prod.admin.datasource.username}                            # mysql数据库账号
    password: ${prod.admin.datasource.password}                            # mysql数据库密码
  data:
    redis:
      host: ${prod.admin.redis.host}                                       #redis 链接
      port: ${prod.admin.redis.port}                                       #redis 端口
      password: ${prod.admin.redis.password}                               #redis 密码
      database: 0                                                         #redis 数据库